name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  lint:
    runs-on: macos-latest
    environment: default
    steps:
      - uses: actions/checkout@v4
      - name: Format lint
        run: swiftformat --lint .
      - name: Lint
        run: swiftlint .
  macos-test:
    environment: default
    strategy:
      matrix:
        include:
          - os: macos-13
            xcode: 14.2 # Swift 5.7
          - os: macos-13
            xcode: 14.3 # Swift 5.8
          - os: macos-13
            xcode: "15.0" # Swift 5.9
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Run Tests
        run: swift test --enable-code-coverage --parallel
      - name: Swift Coverage Report
        run: xcrun llvm-cov export -format="lcov" .build/debug/NetworkServicePackageTests.xctest/Contents/MacOS//NetworkServicePackageTests -instr-profile .build/debug/codecov/default.profdata > coverage_report.lcov
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true # optional (default = false)
