name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  library:
    environment: default
    strategy:
      matrix:
        os:
          - macos-11
          - macos-12
        xcode:
          - '12.4'
          - '12.5.1'
          - '13.2'
          - '13.4'
          - '14.0'
        exclude:
          - os: macos-11
            xcode: '13.2'
          - os: macos-11
            xcode: '13.4'
          - os: macos-11
            xcode: '14.0'
          - os: macos-12
            xcode: '12.4'
          - os: macos-12
            xcode: '12.5.1'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Format lint
        run: swiftformat --lint .
      - name: Lint
        run: swiftlint .
      - name: Run Tests
        run: swift test --enable-code-coverage
      - name: Swift Coverage Report
        uses: maxep/spm-lcov-action@0.3.1
      - name: Code Coverage
        run: bash <(curl -s https://codecov.io/bash) -X xcodellvm
