name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  library:
    environment: default
    strategy:
      matrix:
        os:
          - macos-11
          - macos-12
        xcode:
          - '12.4'
          - '12.5.1'
          - '13.2'
          - '13.4'
          - '14.0.1'
          - '14.1'
          - '14.2'
        exclude:
          - os: macos-11
            xcode: '13.2'
          - os: macos-11
            xcode: '13.4'
          - os: macos-11
            xcode: '14.0.1'
          - os: macos-11
            xcode: '14.1'
          - os: macos-11
            xcode: '14.2'
          - os: macos-12
            xcode: '12.4'
          - os: macos-12
            xcode: '12.5.1'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Format lint
        run: swiftformat --lint .
      - name: Lint
        run: swiftlint .
      - name: Run Tests
        run: swift test --enable-code-coverage --parallel
      - name: Swift Coverage Report
        run: xcrun llvm-cov export -format="lcov" .build/debug/NetworkServicePackageTests.xctest/Contents/MacOS//NetworkServicePackageTests -instr-profile .build/debug/codecov/default.profdata > coverage_report.lcov
      - uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true # optional (default = false)
