name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  library:
    runs-on: macos-11.0
    environment: default
    strategy:
      matrix:
        xcode:
          - '12.4'
          - '12.5.1'
          - '13.2'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # For SonarCloud analysis
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Format lint
        run: swiftformat --lint .
      - name: Lint
        run: swiftlint .
      - name: Run Tests
        run: |
          xcodebuild \
            -scheme NetworkService-Package \
            -destination platform='iOS Simulator',name='iPhone 11' \
            -enableCodeCoverage YES \
            -derivedDataPath output \
            clean \
            test
      - name: Convert Coverage Report
        run: xccov-to-sonarqube-generic.sh output/Logs/Test/*NetworkService-Package-*.xcresult > NetworkService-Package-sonarqube-generic-coverage.xml
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
